### ISSUE TITLE
Example of the database schema

### ISSUE THREAD

**Issue by rainwala** [powerpak/pathospot-compare#1]
Hi, thank you for this great resource. Could you please provide an example schema for the metadata database? I cannot find it anywhere.

**Comment by rainwala** [comment]
nevermind, I found the schema by examining the sqlite db file located here:
/vagrant/example/mrsa.db

**Comment by powerpak** [comment]
Hi there! We are currently writing up documentation for the database schema—but yes, glad you found that you could also examine the example SQLite file. When we do that, we'll link to it from the main README.

Edit: documentation on the schema is now in [README-database.md](https://github.com/powerpak/pathospot-compare/blob/master/README-database.md).
